version: "3.8"

services:

  redis:
    image: bitnami/redis
    restart: unless-stopped
    env_file: .env
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis-data:/bitnami

volumes:
  redis-data: